<div class="hero-unit">
    <h1><?php echo sprintf($this->translate('Welcome to %sZend Framework Bridge%s'), '<span class="zf-green">', '</span>') ?></h1>
    <p><?php echo sprintf($this->translate('Congratulations! You have successfully installed the %sZFBridge Skeleton Application%s. <br />You are currently running Zend Framework version %s. This skeleton can serve as a simple starting point for you to begin building your application on ZF1.'), '<a href="https://github.com/BinaryKitten/ZFSkeletonBridge" target="_blank">', '</a>', Zend_Version::VERSION) ?></p>
</div>