<?php echo $this->doctype(); ?>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('ZFBridge '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0'), "\r\n"; ?>

    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => '/images/favicon.ico'))
                    ->appendStylesheet('/css/bootstrap.min.css')
                    ->appendStylesheet('/css/bootstrap-responsive.min.css'); ?>
    
    
    <?php echo $this->headStyle()->appendStyle("\tbody {\r\n\t\tpadding-top: 60px;\r\n\t\tpadding-bottom: 40px;\r\n\t}"); ?>
    

    <?php echo $this->headScript()->appendFile('/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',)); ?>


    <link rel="author" href="humans.txt" />
  </head>

  <body>

    <div class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">

            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="<?php echo $this->url(array()) ?>"><?php echo $this->translate('Skeleton Application') ?></a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li class="active"><a href="<?php echo $this->url(array()) ?>"><?php echo $this->translate('Home') ?></a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <?php echo $this->layout()->content; ?>

      <hr>

      <footer class="offset10">
        <p>by <a href="https://github.com/BinaryKitten/">BinaryKitten.</a></p>
      </footer>

    </div> <!-- /container -->

    <?php echo $this->inlineScript()
            ->appendFile('/js/jquery-1.8.3.min.js')
            ->appendFile('/js/bootstrap.min.js');
    echo "\r\n"; ?>

  </body>
</html>